### ISSUE TITLE
Super Discord Channel Request

### ISSUE THREAD

**Issue by ark-chatica** [DrDejaVuNG/flutter_super#2]
Can you please create an official discord for the community to grow and ask questions : ) ?

**Comment by DrDejaVuNG** [comment]
As the community is still pretty small it might not yet be necessary, I could go ahead and create a Telegram group now but I will also consider creating a Discord server. How does that sound?

**Comment by ark-chatica** [comment]
That sounds great ! I'll be on the look out for channel when it is created. Thank you.
