### ISSUE TITLE
Do we need something like LaunchedEffect ?

### ISSUE THREAD

**Issue by alexbodymatter** [DrDejaVuNG/flutter_super#4]
Just wondering if we need a way to execute code in response to an observable's value changing. Sort of like LaunchedEffect in Jetpack Compose. 

Also should we start making youtube videos and reddit posts to grow the community ? I've been thinking about making a youtube tutorial on super. Can we have a discord or slack so I can send ideas ?

**Comment by DrDejaVuNG** [comment]
Good Day, regarding the first paragraph, there is a way to execute code whenever an observable's value changes similar to LaunchedEffect and that is by using the rxWatch API. However, unlike the LaunchedEffect, you have to use the observable's value in the function. I don't think I've written it's documentation yet but it's code is sufficiently documented.

As for the second paragraph, It would be amazing if videos, posts etc are created regarding the project as that would be the fastest way to grow the community, if you have any questions while working on your video please don't hesitate to ask I would be very happy to help.

Regarding discussion platforms, I have gone on to create a Discord Server, a lot of things are still amiss but they will be adjusted overtime. This is the link: https://discord.gg/dhY2hXfB

**Comment by alexbodymatter** [comment]
@DrDejaVuNG Discord link seems to be broken. I will be working on videos soon ! Love the library.
